FROM maven:3.8.3-jdk-8-slim

COPY src /usr/src/app/src  
COPY config /usr/src/app/config

COPY pom.xml /usr/src/app
COPY asset-types.properties /usr/src/app

COPY scripts/run.sh /usr/src/app
COPY scripts/lister.sh /usr/src/app
COPY scripts/deleter.sh /usr/src/app

RUN mvn -f /usr/src/app/pom.xml dependency:go-offline
RUN mvn -f /usr/src/app/pom.xml install dependency:copy-dependencies

FROM openjdk:8-jre-slim
COPY --from=build /usr/src/app/ .
COPY --from=build /usr/src/app/target/ ./target/

ENTRYPOINT ["sh", "./run.sh"]